### ISSUE TITLE
Error with ansible step that installs mysql 8 

### ISSUE THREAD

**Issue by mageru** [pboros/mysql8_administration_labs#1]
TASK [common : Install mysql community server 8.0] *****************************
failed: [lab2c] (item=[u'mysql-community-server-8.0.11-1.el7.x86_64']) => {"changed": false, "item": ["mysql-community-server-8.0.11-1.el7.x86_64"], "msg": "warning: /var/cache/yum/x86_64/7/percona-release-x86_64/packages/sysbench-1.0.16-2.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 8507efa5: NOKEY\n\n\nThe GPG keys listed for the \"Percona-Release YUM repository - x86_64\" repository are already installed but they are not correct for this package.\nCheck that the correct key URLs are configured for this repository.\n\n\n Failing package is: sysbench-1.0.16-2.el7.x86_64\n GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Percona\n\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: reflector.westga.edu\n * epel: reflector.westga.edu\n * extras: reflector.westga.edu\n * updates: reflector.westga.edu\nResolving Dependencies\n--> Running transaction check\n---> Package mysql-community-server.x86_64 0:8.0.11-1.el7 will be installed\n--> Processing Dependency: mysql-community-common(x86-64) = 8.0.11-1.el7 for package: mysql-community-server-8.0.11-1.el7.x86_64\n--> Processing Dependency: mysql-community-client(x86-64) >= 8.0.0 for package: mysql-community-server-8.0.11-1.el7.x86_64\n--> Running transaction check\n---> Package mysql-community-client.x86_64 0:8.0.15-1.el7 will be installed\n--> Processing Dependency: mysql-community-libs(x86-64) >= 8.0.0 for package: mysql-community-client-8.0.15-1.el7.x86_64\n---> Package mysql-community-common.x86_64 0:8.0.11-1.el7 will be installed\n--> Running transaction check\n---> Package mariadb-libs.x86_64 1:5.5.56-2.el7 will be obsoleted\n--> Processing Dependency: libmysqlclient.so.18()(64bit) for package: perl-DBD-MySQL-4.023-5.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18()(64bit) for package: sysbench-1.0.14-2.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18()(64bit) for package: 2:postfix-2.10.1-6.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18()(64bit) for package: MySQL-python-1.2.5-1.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18(libmysqlclient_18)(64bit) for package: perl-DBD-MySQL-4.023-5.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18(libmysqlclient_18)(64bit) for package: sysbench-1.0.14-2.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18(libmysqlclient_18)(64bit) for package: 2:postfix-2.10.1-6.el7.x86_64\n--> Processing Dependency: libmysqlclient.so.18(libmysqlclient_18)(64bit) for package: MySQL-python-1.2.5-1.el7.x86_64\n---> Package mysql-community-libs.x86_64 0:8.0.15-1.el7 will be obsoleting\n--> Running transaction check\n---> Package Percona-XtraDB-Cluster-shared-compat-57.x86_64 0:5.7.24-31.33.1.el7 will be obsoleting\n---> Package perl-DBD-MySQL.x86_64 0:4.023-5.el7 will be updated\n---> Package perl-DBD-MySQL.x86_64 0:4.023-6.el7 will be an update\n---> Package postfix.x86_64 2:2.10.1-6.el7 will be updated\n---> Package postfix.x86_64 2:2.10.1-7.el7 will be an update\n---> Package sysbench.x86_64 0:1.0.14-2.el7 will be updated\n---> Package sysbench.x86_64 0:1.0.16-2.el7 will be an update\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                 Arch   Version            Repository              Size\n================================================================================\nInstalling:\n Percona-XtraDB-Cluster-shared-compat-57\n                         x86_64 5.7.24-31.33.1.el7 percona-release-x86_64 1.1 M\n     replacing  mariadb-libs.x86_64 1:5.5.56-2.el7\n mysql-community-libs    x86_64 8.0.15-1.el7       mysql80-community      2.2 M\n     replacing  mariadb-libs.x86_64 1:5.5.56-2.el7\n mysql-community-server  x86_64 8.0.11-1.el7       mysql80-community      341 M\nInstalling for dependencies:\n mysql-community-client  x86_64 8.0.15-1.el7       mysql80-community       25 M\n mysql-community-common  x86_64 8.0.11-1.el7       mysql80-community      537 k\nUpdating for dependencies:\n perl-DBD-MySQL          x86_64 4.023-6.el7        base                   140 k\n postfix                 x86_64 2:2.10.1-7.el7     base                   2.4 M\n sysbench                x86_64 1.0.16-2.el7       percona-release-x86_64 436 k\n\nTransaction Summary\n================================================================================\nInstall  3 Packages (+2 Dependent packages)\nUpgrade             ( 3 Dependent packages)\n\nTotal size: 373 M\nTotal download size: 32 M\nDownloading packages:\nDelta RPMs disabled because /usr/bin/applydeltarpm not installed.\nPublic key for sysbench-1.0.16-2.el7.x86_64.rpm is not installed\n--------------------------------------------------------------------------------\nTotal                                              6.6 MB/s |  32 MB  00:04     \nRetrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Percona\n"]}
	to retry, use: --limit @/ansible/master_local.retry

PLAY RECAP *********************************************************************
lab2c                      : ok=7    changed=3    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
~/D/m/lab2c ❯❯❯

**Comment by pboros** [comment]
Thanks for the report @mageru . Is it failing consistently at that point? If you do vagrant destroy -f and vagrant up again? I don't see any failure in that output, looks like it just could not download packages in time. Which is surprising since the download speed seems ok.

**Comment by pboros** [comment]
@mageru The issue was because of GPG checking, I pushed a change to turn them off, do a git pull on this repo and you should be ok. I also updated the virtualbox images to 1.0, which are based on centos 7.6 and was virtualbox guest additions from 5.2.26 (5.1 series no longer works on Mac OS X mojave, which is my host). 

Make sure you destroy your old environments, do a git pull and this issue should be fixed. I also updated to instructions to skip the GPG check where applicable.
