### ISSUE TITLE
Problem with lab2a

### ISSUE THREAD

**Issue by ghost** [pboros/mysql8_administration_labs#2]
Hi Peter, 
Bought your course Mysql 8 for Admins from packtpub. 
I got interested in the vagrant and virtualbox usage you used in this course.
I installed vagrant 2.2.4 and virtualbox 6.04 on my Ubuntu 18.10 computer.
Lab0  and lab1c went fine. 
Starting with lab2a I got errors. 
I'm not (yet) familiar  with ansible and buildbox code.

The errors i got are shown below in bold
The download is redirected, why and how, is this the cause of the write failed?
Regards Wim Slangewal and nice course! 

================================================================
wim@WD001:~/vagrant/PROJECTS/mysql8_administration_labs/lab2a$ vagrant up
Bringing machine 'lab2a' up with 'virtualbox' provider...
==> lab2a: Box 'pboros/mysql8_admin_80' could not be found. Attempting to find and install...
    lab2a: Box Provider: virtualbox
    lab2a: Box Version: 1.0
==> lab2a: Loading metadata for box 'pboros/mysql8_admin_80'
    lab2a: URL: https://vagrantcloud.com/pboros/mysql8_admin_80
==> lab2a: Adding box 'pboros/mysql8_admin_80' (v1.0) for provider: virtualbox
    lab2a: Downloading: https://vagrantcloud.com/pboros/boxes/mysql8_admin_80/versions/1.0/providers/virtualbox.box
    **lab2a: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com**
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
**x centos-7.6-x86_64-disk001.vmdk: Write failed
x metadata.json: Write failed**
bsdtar: Error exit delayed from previous errors.

**Comment by pboros** [comment]
You probably need to re-download the box. I no longer maintain this repository, the course is no longer available.
