### ISSUE TITLE
unable to build lab4d

### ISSUE THREAD

**Issue by mmadhavarao** [pboros/mysql8_administration_labs#4]
getting the below error , any resolution for below issue ? plz share . 
I am using Virtual box 6.1.26 , running on Windows 10 

PLAY RECAP *********************************************************************
lab4d-sysbench             : ok=13   changed=7    unreachable=0    failed=0

==> lab4d-db1: Running provisioner: ansible_local...
    lab4d-db1: Running ansible-playbook...

PLAY [lab4d-db2] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [lab4d-db2]

TASK [Get change master sql] ***************************************************
ok: [lab4d-db2]

TASK [Configure replication] ***************************************************
changed: [lab4d-db2]

TASK [Reset master] ************************************************************
changed: [lab4d-db2]

TASK [Start listener on target] ************************************************
changed: [lab4d-db2]

PLAY [lab4d-db1] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [lab4d-db1]

TASK [Stream backup to target] *************************************************
fatal: [lab4d-db1]: FAILED! => {"changed": true, "cmd": "mysqldump --all-databases --triggers --routines --events --master-data=1 --single-transaction | socat -u - tcp:lab4d-db2:4444", "delta": "0:00:01.074018", "end": "2021-11-09 14:59:28.735403", "msg": "non-zero return code", "rc": 1, "start": "2021-11-09 14:59:27.661385", "stderr": "2021/11/09 14:59:28 socat[9707] E write(5, 0x5614c34232a0, 2613): Broken pipe\nmysqldump: Got errno 11 on write", "stderr_lines": ["2021/11/09 14:59:28 socat[9707] E write(5, 0x5614c34232a0, 2613): Broken pipe", "mysqldump: Got errno 11 on write"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/ansible/clone.retry

PLAY RECAP *********************************************************************
lab4d-db1                  : ok=1    changed=0    unreachable=0    failed=1
lab4d-db2                  : ok=5    changed=3    unreachable=0    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by pboros** [comment]
Broken pipe indicates some issues with the virtual network, I would check the networks defined at the virtualbox level. This is outside of vagrant's control. If you would like to have a clean and simple solution, just use a virtualbox where you don't have any network level custom configuration. Let me know how it goes.

**Comment by mmadhavarao** [comment]
> Broken pipe indicates some issues with the virtual network, I would check the networks defined at the virtualbox level. This is outside of vagrant's control. If you would like to have a clean and simple solution, just use a virtualbox where you don't have any network level custom configuration. Let me know how it goes.

Thanks Peter , tried doing it with fresh virtualbox and vagrant (after uninstalling everything) , still got the same .
also attached below the screen from virtualbox / host network manager window

------ERROR-------------------
------------------------------------

TASK [Gathering Facts] *********************************************************
ok: [lab4d-db1]

TASK [Stream backup to target] *************************************************
fatal: [lab4d-db1]: FAILED! => {"changed": true, "cmd": "mysqldump --all-databases --triggers --routines --events --master-data=1 --single-transaction | socat -u - tcp:lab4d-db2:4444", "delta": "0:00:08.432684", "end": "2021-11-11 09:19:42.246070", "msg": "non-zero return code", "rc": 1, "start": "2021-11-11 09:19:33.813386", "stderr": "2021/11/11 09:19:40 socat[9659] E write(5, 0x55d7468562a0, 927): Broken pipe\nmysqldump: Got errno 32 on write", "stderr_lines": ["2021/11/11 09:19:40 socat[9659] E write(5, 0x55d7468562a0, 927): Broken pipe", "mysqldump: Got errno 32 on write"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/ansible/clone.retry

PLAY RECAP *********************************************************************
lab4d-db1                  : ok=1    changed=0    unreachable=0    failed=1
lab4d-db2                  : ok=5    changed=3    unreachable=0    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

![image](https://user-images.githubusercontent.com/85154425/141275193-d63100be-3261-4fd0-9635-d073ef8a31b8.png)

**Comment by mmadhavarao** [comment]
> Broken pipe", "mysqldump: Got errno 32 on write"

The issue may be because of this switch in “mysqldump” as this is depreciated from 8.0.26

	 
![image](https://user-images.githubusercontent.com/85154425/141602077-04459bb0-5192-4240-ab50-d96e1a3255df.png)


Modified the file “clone.yml” in path .\ansible\clone.yml as below and the lab went fine
	Ie.. removed –master-data=1 in below mysqldump command.

	  
![image](https://user-images.githubusercontent.com/85154425/141602081-21543fce-7400-4718-a3cd-9cac9b4437b9.png)

**Comment by pboros** [comment]
Good catch, it's not deprecated it's renamed, I will push a change with the rename to this repo, let me try first with brand new images.

**Comment by pboros** [comment]
I changed the code, pull the repo and try now. If you just remove the master-data other things will break. Thanks for your help finding this.

**Comment by mmadhavarao** [comment]
> I changed the code, pull the repo and try now. If you just remove the master-data other things will break. Thanks for your help finding this.

Thanks Peter , yeah its working now :-)
